# Generated by Django 3.0.1 on 2019-12-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активность')),
                ('url', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('description', models.TextField(verbose_name='Текст страницы')),
            ],
        ),
    ]
