# Generated by Django 3.0.1 on 2020-01-08 12:14

from django.db import migrations

def create_no_category(apps, schema_editor):
    Category = apps.get_model('pages', 'Category')
    no_category = Category(name='Без категории', url='')
    no_category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200108_1356'),
    ]

    operations = [
            migrations.RunPython(create_no_category),
    ]
