# Generated by Django 3.0.1 on 2020-01-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200108_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.Category'),
        ),
    ]
