# Generated by Django 3.0.6 on 2020-05-15 14:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200515_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
