# Generated by Django 3.0.6 on 2020-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(max_length=100, verbose_name='Изображение'),
        ),
    ]
