# Generated by Django 3.0.6 on 2020-07-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200730_1601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersettings',
            table='accounts_user_settings',
        ),
    ]
