# Generated by Django 3.0.1 on 2020-01-14 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('url', models.SlugField(unique=True, verbose_name='ЧПУ')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активность')),
                ('url', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('title', models.CharField(max_length=100, verbose_name='Название публикации')),
                ('description', models.TextField(verbose_name='Текст публикации')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='publications.Category')),
            ],
        ),
    ]
